# run tests in the Julia image provided by BI-JUL
tests:
  image: ${CI_REGISTRY}/bi-jul/bi-jul:latest
  stage: test
  script:
    - julia --version
    - julia --project=@. -e 'import Pkg; Pkg.instantiate()'
    - julia --project=@. --color=yes test/runtests.jl
